version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '08:00'
    open-pull-requests-limit: 10
    labels: [dependencies]
    groups:
      types:
        patterns: ['@types/*']
      aws-cdk:
        patterns: ['aws-cdk*', '@aws-cdk/*']
      expo:
        patterns: ['expo*', '@expo/*']
      tamagui:
        patterns: ['@tamagui/*', 'tamagui']
      eslint:
        patterns: ['eslint*', '@typescript-eslint/*']
      jest:
        patterns: ['jest*', '@types/jest']

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies, ci]
