#!/usr/bin/env node
/**
 * Export CDK stack outputs to .env.local files for mobile app
 * Run after: pnpm cdk:deploy
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const env = process.env.ENV || process.argv[2] || 'dev';

console.log(`📦 Exporting CDK outputs for environment: ${env}`);

try {
  // Get CloudFormation stack names for this environment
  const stacks = [
    `WFL-Auth-${env}`,
    `WFL-API-${env}`,
    `WFL-AI-${env}`,
    `WFL-Data-${env}`,
  ];

  const outputs = {};

  for (const stackName of stacks) {
    try {
      const result = execSync(
        `aws cloudformation describe-stacks --stack-name ${stackName} --query "Stacks[0].Outputs" --output json`,
        { encoding: 'utf8' }
      );
      const stackOutputs = JSON.parse(result);

      for (const output of stackOutputs || []) {
        outputs[output.OutputKey] = output.OutputValue;
      }
    } catch (err) {
      console.warn(`⚠️  Stack ${stackName} not found (might not be deployed yet)`);
    }
  }

  // Map CDK outputs to environment variables
  const envContent = `
# WhatsForLunch Local Development Environment
# Generated by: pnpm cdk:outputs
# Last updated: ${new Date().toISOString()}

# Cognito (Auth)
EXPO_PUBLIC_COGNITO_USER_POOL_ID=${outputs['UserPoolId'] || 'CONFIGURE_ME'}
EXPO_PUBLIC_COGNITO_CLIENT_ID=${outputs['WebClientId'] || 'CONFIGURE_ME'}
EXPO_PUBLIC_COGNITO_REGION=${process.env.AWS_REGION || 'us-east-1'}
EXPO_PUBLIC_COGNITO_IDENTITY_POOL_ID=${outputs['IdentityPoolId'] || 'CONFIGURE_ME'}

# AppSync GraphQL API
EXPO_PUBLIC_APPSYNC_ENDPOINT=${outputs['AppSyncApiUrl'] || 'CONFIGURE_ME'}
EXPO_PUBLIC_APPSYNC_API_KEY=${outputs['AppSyncApiKey'] || 'CONFIGURE_ME'}
EXPO_PUBLIC_APPSYNC_REGION=${process.env.AWS_REGION || 'us-east-1'}

# S3
EXPO_PUBLIC_S3_BUCKET_PHOTOS=${outputs['PhotosBucket'] || 'CONFIGURE_ME'}
EXPO_PUBLIC_S3_REGION=${process.env.AWS_REGION || 'us-east-1'}

# Environment
EXPO_PUBLIC_ENV=${env}
EXPO_PUBLIC_API_STAGE=${env}
`.trim();

  const envFilePath = path.join(__dirname, '../../apps/mobile/.env.local');
  const envDir = path.dirname(envFilePath);

  if (!fs.existsSync(envDir)) {
    fs.mkdirSync(envDir, { recursive: true });
  }

  fs.writeFileSync(envFilePath, envContent + '\n');

  console.log(`✅ Environment file created: apps/mobile/.env.local`);
  console.log(`\n📝 Manual setup steps (if not auto-configured):`);
  console.log(`   1. Run: aws configure sso --profile wfl-dev`);
  console.log(`   2. Run: pnpm --filter @wfl/infra cdk deploy --all --context env=${env}`);
  console.log(`   3. Run: pnpm --filter @wfl/infra cdk:outputs`);

} catch (error) {
  console.error('❌ Error exporting outputs:', error.message);
  process.exit(1);
}
