import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 6,
  tables: [
    tableSchema({
      name: 'profiles',
      columns: [
        { name: 'cloud_id', type: 'string', isIndexed: true },
        { name: 'email', type: 'string', isIndexed: true },
        { name: 'display_name', type: 'string', isOptional: true },
        { name: 'photo_url', type: 'string', isOptional: true },
        { name: 'time_zone', type: 'string' },
        { name: 'units', type: 'string' },
        { name: 'subscription_tier', type: 'string' },
        { name: 'ai_quota_used_today', type: 'number' },
        { name: 'digest_enabled', type: 'boolean' },
        { name: 'digest_time', type: 'string' },
        { name: 'digest_timezone', type: 'string' },
        { name: 'digest_last_sent_at', type: 'number', isOptional: true },
        { name: '_version', type: 'number' },
        { name: '_last_changed_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'households',
      columns: [
        { name: 'cloud_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'owner_id', type: 'string' },
        { name: 'member_count', type: 'number' },
        { name: '_version', type: 'number' },
        { name: '_last_changed_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'household_members',
      columns: [
        { name: 'cloud_id', type: 'string', isIndexed: true },
        { name: 'household_id', type: 'string', isIndexed: true },
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'display_name', type: 'string', isOptional: true },
        { name: 'role', type: 'string' },
        { name: 'joined_at', type: 'number' },
        { name: '_version', type: 'number' },
        { name: '_last_changed_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'containers',
      columns: [
        { name: 'cloud_id', type: 'string', isIndexed: true },
        { name: 'qr_token', type: 'string', isIndexed: true },
        { name: 'qr_number', type: 'number', isOptional: true },
        { name: 'household_id', type: 'string', isIndexed: true },
        { name: 'nickname', type: 'string', isOptional: true },
        { name: 'image_url', type: 'string', isOptional: true },
        { name: 'claimed_at', type: 'number' },
        { name: 'archived_at', type: 'number', isOptional: true },
        { name: '_version', type: 'number' },
        { name: '_last_changed_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'items',
      columns: [
        { name: 'cloud_id', type: 'string', isIndexed: true },
        { name: 'household_id', type: 'string', isIndexed: true },
        { name: 'container_id', type: 'string', isIndexed: true, isOptional: true },
        { name: 'added_by_user_id', type: 'string' },
        { name: 'food_type', type: 'string' },
        { name: 'food_name', type: 'string' },
        { name: 'category', type: 'string' },
        { name: 'storage_location', type: 'string' },
        { name: 'quantity_text', type: 'string', isOptional: true },
        { name: 'quantity_value', type: 'number', isOptional: true },
        { name: 'quantity_unit', type: 'string', isOptional: true },
        { name: 'stored_at', type: 'number' },
        { name: 'stored_tz', type: 'string' },
        { name: 'expiry_at', type: 'number', isIndexed: true },
        { name: 'expiry_source', type: 'string' },
        { name: 'expiry_confidence', type: 'number', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'photo_url', type: 'string', isOptional: true },
        { name: 'barcode', type: 'string', isOptional: true },
        { name: 'calories_per_100g', type: 'number', isOptional: true },
        { name: 'protein_per_100g', type: 'number', isOptional: true },
        { name: 'carbs_per_100g', type: 'number', isOptional: true },
        { name: 'fat_per_100g', type: 'number', isOptional: true },
        { name: 'fiber_per_100g', type: 'number', isOptional: true },
        { name: 'sugar_per_100g', type: 'number', isOptional: true },
        { name: 'sodium_per_100g', type: 'number', isOptional: true },
        { name: 'price_usd', type: 'number', isOptional: true },
        { name: 'status', type: 'string', isIndexed: true },
        { name: 'eaten_at', type: 'number', isOptional: true },
        { name: 'tossed_at', type: 'number', isOptional: true },
        { name: 'frozen_at', type: 'number', isOptional: true },
        { name: 'transferred_to_container_id', type: 'string', isOptional: true },
        { name: '_version', type: 'number' },
        { name: '_last_changed_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'food_rules',
      columns: [
        { name: 'cloud_id', type: 'string', isIndexed: true },
        { name: 'food_type', type: 'string', isIndexed: true },
        { name: 'display_name', type: 'string' },
        { name: 'category', type: 'string' },
        { name: 'aliases_json', type: 'string' },
        { name: 'fridge_days_safe', type: 'number', isOptional: true },
        { name: 'freezer_days_safe', type: 'number', isOptional: true },
        { name: 'pantry_days_safe', type: 'number', isOptional: true },
        { name: 'counter_hours_safe', type: 'number', isOptional: true },
        { name: 'icon_key', type: 'string', isOptional: true },
        { name: '_version', type: 'number' },
        { name: '_last_changed_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'item_events',
      columns: [
        { name: 'cloud_id', type: 'string', isIndexed: true },
        { name: 'item_id', type: 'string', isIndexed: true },
        { name: 'actor_user_id', type: 'string' },
        { name: 'event_type', type: 'string' },
        { name: 'payload_json', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'shopping_list_items',
      columns: [
        { name: 'cloud_id', type: 'string', isIndexed: true },
        { name: 'household_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'quantity', type: 'string', isOptional: true },
        { name: 'category', type: 'string', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'added_by_user_id', type: 'string' },
        { name: 'purchased_at', type: 'number', isOptional: true },
        { name: 'purchased_by_user_id', type: 'string', isOptional: true },
        { name: 'auto_suggested', type: 'boolean' },
        { name: '_version', type: 'number' },
        { name: '_last_changed_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'meal_plan_entries',
      columns: [
        { name: 'cloud_id', type: 'string', isIndexed: true },
        { name: 'household_id', type: 'string', isIndexed: true },
        { name: 'added_by_user_id', type: 'string' },
        { name: 'recipe_cloud_id', type: 'string', isOptional: true },
        { name: 'recipe_snapshot_json', type: 'string', isOptional: true },
        { name: 'planned_for_at', type: 'number', isIndexed: true },
        { name: 'meal_type', type: 'string' },
        { name: 'servings', type: 'number', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: '_version', type: 'number' },
        { name: '_last_changed_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'activities',
      columns: [
        { name: 'cloud_id', type: 'string', isIndexed: true },
        { name: 'household_id', type: 'string', isIndexed: true },
        { name: 'actor_id', type: 'string', isIndexed: true },
        { name: 'action', type: 'string' },
        { name: 'resource_type', type: 'string' },
        { name: 'resource_id', type: 'string' },
        { name: 'resource_data_json', type: 'string', isOptional: true },
        { name: 'timestamp', type: 'number', isIndexed: true },
        { name: '_version', type: 'number' },
        { name: '_last_changed_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'learned_preferences',
      columns: [
        { name: 'user_id', type: 'string', isIndexed: true },
        { name: 'top_eaten_json', type: 'string', isOptional: true },
        { name: 'top_tossed_json', type: 'string', isOptional: true },
        { name: 'cuisine_affinity_json', type: 'string', isOptional: true },
        { name: 'last_updated_at', type: 'number', isIndexed: true },
        { name: '_version', type: 'number' },
        { name: '_last_changed_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'saved_recipes',
      columns: [
        { name: 'cloud_id', type: 'string', isIndexed: true },
        { name: 'household_id', type: 'string', isIndexed: true },
        { name: 'recipe_id', type: 'string' },
        { name: 'title', type: 'string' },
        { name: 'image_url', type: 'string', isOptional: true },
        { name: 'rating', type: 'number', isOptional: true },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'saved_at', type: 'number', isIndexed: true },
        { name: '_version', type: 'number' },
        { name: '_last_changed_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
  ],
});
