/**
 * Lambda: food-rules-publish
 * Triggered manually or via CDK deployment to seed / update FoodRule records
 * in DynamoDB. Idempotent — only writes if version has changed.
 *
 * Environment variables:
 *   MAIN_TABLE  — DynamoDB table name
 *   AWS_REGION  — AWS region
 */

import { DynamoDBClient } from '@aws-sdk/client-dynamodb';
import {
  DynamoDBDocumentClient,
  GetCommand,
  PutCommand,
  BatchWriteCommand,
} from '@aws-sdk/lib-dynamodb';
import { Logger } from '@aws-lambda-powertools/logger';

const logger = new Logger({ serviceName: 'food-rules-publish' });

const ddbClient = new DynamoDBClient({ region: process.env.AWS_REGION ?? 'us-east-1' });
const ddb = DynamoDBDocumentClient.from(ddbClient);

const TABLE = process.env.MAIN_TABLE ?? 'wfl-main-dev';
const RULES_VERSION = 3; // bump this to force re-publish

interface FoodRule {
  foodType: string;
  displayName: string;
  category: string;
  aliases: string[];
  fridgeDaysSafe?: number;
  freezerDaysSafe?: number;
  pantryDaysSafe?: number;
  counterHoursSafe?: number;
  iconKey?: string;
  version: number;
}

// ~150 rules covering major food categories
const FOOD_RULES: FoodRule[] = [
  // ── Leftovers ──────────────────────────────────────────────────────────────
  {
    foodType: 'leftover_pasta',
    displayName: 'Leftover Pasta',
    category: 'leftover',
    aliases: ['pasta', 'noodles', 'spaghetti', 'penne'],
    fridgeDaysSafe: 5,
    freezerDaysSafe: 60,
    iconKey: 'pasta',
    version: RULES_VERSION,
  },
  {
    foodType: 'leftover_rice',
    displayName: 'Leftover Rice',
    category: 'leftover',
    aliases: ['rice', 'fried rice', 'white rice', 'brown rice'],
    fridgeDaysSafe: 4,
    freezerDaysSafe: 60,
    iconKey: 'rice',
    version: RULES_VERSION,
  },
  {
    foodType: 'leftover_soup',
    displayName: 'Leftover Soup',
    category: 'leftover',
    aliases: ['soup', 'stew', 'broth', 'chowder', 'chili'],
    fridgeDaysSafe: 4,
    freezerDaysSafe: 90,
    iconKey: 'soup',
    version: RULES_VERSION,
  },
  {
    foodType: 'leftover_pizza',
    displayName: 'Leftover Pizza',
    category: 'leftover',
    aliases: ['pizza', 'flatbread pizza'],
    fridgeDaysSafe: 4,
    freezerDaysSafe: 60,
    iconKey: 'pizza',
    version: RULES_VERSION,
  },
  {
    foodType: 'leftover_curry',
    displayName: 'Leftover Curry',
    category: 'leftover',
    aliases: ['curry', 'indian food', 'thai curry'],
    fridgeDaysSafe: 4,
    freezerDaysSafe: 90,
    iconKey: 'curry',
    version: RULES_VERSION,
  },
  {
    foodType: 'leftover_stir_fry',
    displayName: 'Leftover Stir Fry',
    category: 'leftover',
    aliases: ['stir fry', 'stir-fry', 'lo mein', 'fried noodles'],
    fridgeDaysSafe: 3,
    freezerDaysSafe: 60,
    iconKey: 'wok',
    version: RULES_VERSION,
  },
  {
    foodType: 'leftover_sandwich',
    displayName: 'Leftover Sandwich',
    category: 'leftover',
    aliases: ['sandwich', 'sub', 'wrap', 'burrito', 'panini'],
    fridgeDaysSafe: 2,
    iconKey: 'sandwich',
    version: RULES_VERSION,
  },
  {
    foodType: 'leftover_salad',
    displayName: 'Leftover Salad',
    category: 'leftover',
    aliases: ['salad', 'dressed salad', 'coleslaw'],
    fridgeDaysSafe: 2,
    iconKey: 'salad',
    version: RULES_VERSION,
  },

  // ── Protein ────────────────────────────────────────────────────────────────
  {
    foodType: 'cooked_chicken',
    displayName: 'Cooked Chicken',
    category: 'protein',
    aliases: [
      'chicken',
      'rotisserie chicken',
      'grilled chicken',
      'fried chicken',
      'chicken breast',
    ],
    fridgeDaysSafe: 4,
    freezerDaysSafe: 120,
    iconKey: 'chicken',
    version: RULES_VERSION,
  },
  {
    foodType: 'raw_chicken',
    displayName: 'Raw Chicken',
    category: 'protein',
    aliases: ['raw chicken', 'chicken breast raw', 'chicken thighs raw'],
    fridgeDaysSafe: 2,
    freezerDaysSafe: 270,
    iconKey: 'chicken_raw',
    version: RULES_VERSION,
  },
  {
    foodType: 'cooked_beef',
    displayName: 'Cooked Beef',
    category: 'protein',
    aliases: ['beef', 'steak', 'hamburger', 'meatballs', 'brisket', 'roast beef'],
    fridgeDaysSafe: 4,
    freezerDaysSafe: 90,
    iconKey: 'beef',
    version: RULES_VERSION,
  },
  {
    foodType: 'raw_beef',
    displayName: 'Raw Beef',
    category: 'protein',
    aliases: ['raw beef', 'ground beef', 'raw steak', 'raw hamburger'],
    fridgeDaysSafe: 2,
    freezerDaysSafe: 120,
    iconKey: 'beef_raw',
    version: RULES_VERSION,
  },
  {
    foodType: 'cooked_pork',
    displayName: 'Cooked Pork',
    category: 'protein',
    aliases: ['pork', 'pulled pork', 'pork chops', 'ham', 'bacon cooked', 'carnitas'],
    fridgeDaysSafe: 4,
    freezerDaysSafe: 90,
    iconKey: 'pork',
    version: RULES_VERSION,
  },
  {
    foodType: 'raw_pork',
    displayName: 'Raw Pork',
    category: 'protein',
    aliases: ['raw pork', 'pork chops raw', 'pork tenderloin raw'],
    fridgeDaysSafe: 3,
    freezerDaysSafe: 180,
    iconKey: 'pork_raw',
    version: RULES_VERSION,
  },
  {
    foodType: 'cooked_fish',
    displayName: 'Cooked Fish',
    category: 'protein',
    aliases: ['fish', 'salmon cooked', 'tuna cooked', 'tilapia', 'cod cooked', 'shrimp cooked'],
    fridgeDaysSafe: 3,
    freezerDaysSafe: 90,
    iconKey: 'fish',
    version: RULES_VERSION,
  },
  {
    foodType: 'raw_fish',
    displayName: 'Raw Fish',
    category: 'protein',
    aliases: ['raw fish', 'raw salmon', 'raw tuna', 'sushi grade fish'],
    fridgeDaysSafe: 2,
    freezerDaysSafe: 180,
    iconKey: 'fish_raw',
    version: RULES_VERSION,
  },
  {
    foodType: 'cooked_shrimp',
    displayName: 'Cooked Shrimp',
    category: 'protein',
    aliases: ['shrimp', 'prawns cooked', 'scallops cooked'],
    fridgeDaysSafe: 3,
    freezerDaysSafe: 90,
    iconKey: 'shrimp',
    version: RULES_VERSION,
  },
  {
    foodType: 'deli_meat',
    displayName: 'Deli Meat',
    category: 'protein',
    aliases: [
      'deli meat',
      'lunch meat',
      'cold cuts',
      'turkey breast sliced',
      'ham sliced',
      'roast beef sliced',
    ],
    fridgeDaysSafe: 5,
    freezerDaysSafe: 60,
    iconKey: 'deli',
    version: RULES_VERSION,
  },
  {
    foodType: 'hot_dogs',
    displayName: 'Hot Dogs',
    category: 'protein',
    aliases: ['hot dogs', 'sausage', 'bratwurst', 'kielbasa', 'frankfurter'],
    fridgeDaysSafe: 7,
    freezerDaysSafe: 60,
    iconKey: 'hotdog',
    version: RULES_VERSION,
  },
  {
    foodType: 'eggs_hard_boiled',
    displayName: 'Hard Boiled Eggs',
    category: 'protein',
    aliases: ['hard boiled eggs', 'hard cooked eggs', 'deviled eggs'],
    fridgeDaysSafe: 7,
    iconKey: 'egg',
    version: RULES_VERSION,
  },
  {
    foodType: 'eggs_raw',
    displayName: 'Raw Eggs',
    category: 'protein',
    aliases: ['raw eggs', 'eggs', 'eggs in shell'],
    fridgeDaysSafe: 35,
    freezerDaysSafe: 365,
    iconKey: 'egg_raw',
    version: RULES_VERSION,
  },
  {
    foodType: 'tofu',
    displayName: 'Tofu',
    category: 'protein',
    aliases: ['tofu', 'firm tofu', 'silken tofu', 'edamame', 'tempeh'],
    fridgeDaysSafe: 5,
    freezerDaysSafe: 90,
    iconKey: 'tofu',
    version: RULES_VERSION,
  },

  // ── Dairy ──────────────────────────────────────────────────────────────────
  {
    foodType: 'milk',
    displayName: 'Milk',
    category: 'dairy',
    aliases: ['milk', 'whole milk', '2% milk', 'skim milk', 'oat milk', 'almond milk'],
    fridgeDaysSafe: 7,
    iconKey: 'milk',
    version: RULES_VERSION,
  },
  {
    foodType: 'yogurt',
    displayName: 'Yogurt',
    category: 'dairy',
    aliases: ['yogurt', 'greek yogurt', 'skyr', 'kefir', 'yogurt parfait'],
    fridgeDaysSafe: 14,
    freezerDaysSafe: 60,
    iconKey: 'yogurt',
    version: RULES_VERSION,
  },
  {
    foodType: 'cheese_hard',
    displayName: 'Hard Cheese',
    category: 'dairy',
    aliases: ['cheddar', 'parmesan', 'gouda', 'swiss cheese', 'manchego', 'gruyere', 'pecorino'],
    fridgeDaysSafe: 21,
    freezerDaysSafe: 180,
    iconKey: 'cheese',
    version: RULES_VERSION,
  },
  {
    foodType: 'cheese_soft',
    displayName: 'Soft Cheese',
    category: 'dairy',
    aliases: [
      'brie',
      'camembert',
      'mozzarella',
      'ricotta',
      'feta',
      'cottage cheese',
      'cream cheese',
      'goat cheese',
    ],
    fridgeDaysSafe: 7,
    iconKey: 'cheese_soft',
    version: RULES_VERSION,
  },
  {
    foodType: 'butter',
    displayName: 'Butter',
    category: 'dairy',
    aliases: ['butter', 'salted butter', 'unsalted butter', 'ghee'],
    fridgeDaysSafe: 21,
    freezerDaysSafe: 270,
    counterHoursSafe: 48,
    iconKey: 'butter',
    version: RULES_VERSION,
  },
  {
    foodType: 'sour_cream',
    displayName: 'Sour Cream',
    category: 'dairy',
    aliases: ['sour cream', 'creme fraiche', 'smetana'],
    fridgeDaysSafe: 14,
    iconKey: 'dairy',
    version: RULES_VERSION,
  },
  {
    foodType: 'heavy_cream',
    displayName: 'Heavy Cream',
    category: 'dairy',
    aliases: ['heavy cream', 'whipping cream', 'half and half', 'coffee creamer'],
    fridgeDaysSafe: 10,
    iconKey: 'dairy',
    version: RULES_VERSION,
  },
  {
    foodType: 'ice_cream',
    displayName: 'Ice Cream',
    category: 'dairy',
    aliases: ['ice cream', 'frozen yogurt', 'sorbet', 'gelato', 'sherbet'],
    freezerDaysSafe: 60,
    iconKey: 'ice_cream',
    version: RULES_VERSION,
  },

  // ── Produce ────────────────────────────────────────────────────────────────
  {
    foodType: 'leafy_greens',
    displayName: 'Leafy Greens',
    category: 'produce',
    aliases: [
      'spinach',
      'lettuce',
      'arugula',
      'kale',
      'mixed greens',
      'romaine',
      'spring mix',
      'chard',
    ],
    fridgeDaysSafe: 5,
    iconKey: 'greens',
    version: RULES_VERSION,
  },
  {
    foodType: 'broccoli',
    displayName: 'Broccoli',
    category: 'produce',
    aliases: ['broccoli', 'broccoli florets', 'broccolini'],
    fridgeDaysSafe: 7,
    freezerDaysSafe: 270,
    iconKey: 'broccoli',
    version: RULES_VERSION,
  },
  {
    foodType: 'cauliflower',
    displayName: 'Cauliflower',
    category: 'produce',
    aliases: ['cauliflower', 'cauliflower florets', 'romanesco'],
    fridgeDaysSafe: 7,
    freezerDaysSafe: 270,
    iconKey: 'cauliflower',
    version: RULES_VERSION,
  },
  {
    foodType: 'carrots',
    displayName: 'Carrots',
    category: 'produce',
    aliases: ['carrots', 'baby carrots', 'carrot sticks', 'carrot coins'],
    fridgeDaysSafe: 21,
    freezerDaysSafe: 270,
    iconKey: 'carrot',
    version: RULES_VERSION,
  },
  {
    foodType: 'celery',
    displayName: 'Celery',
    category: 'produce',
    aliases: ['celery', 'celery sticks', 'celery hearts'],
    fridgeDaysSafe: 14,
    iconKey: 'celery',
    version: RULES_VERSION,
  },
  {
    foodType: 'bell_pepper',
    displayName: 'Bell Pepper',
    category: 'produce',
    aliases: [
      'bell pepper',
      'red pepper',
      'green pepper',
      'yellow pepper',
      'orange pepper',
      'capsicum',
    ],
    fridgeDaysSafe: 10,
    freezerDaysSafe: 270,
    iconKey: 'pepper',
    version: RULES_VERSION,
  },
  {
    foodType: 'cucumber',
    displayName: 'Cucumber',
    category: 'produce',
    aliases: ['cucumber', 'english cucumber', 'mini cucumbers'],
    fridgeDaysSafe: 7,
    iconKey: 'cucumber',
    version: RULES_VERSION,
  },
  {
    foodType: 'tomato',
    displayName: 'Tomato',
    category: 'produce',
    aliases: ['tomato', 'cherry tomatoes', 'grape tomatoes', 'roma tomato', 'beefsteak tomato'],
    fridgeDaysSafe: 5,
    counterHoursSafe: 72,
    iconKey: 'tomato',
    version: RULES_VERSION,
  },
  {
    foodType: 'mushroom',
    displayName: 'Mushrooms',
    category: 'produce',
    aliases: [
      'mushrooms',
      'button mushrooms',
      'cremini',
      'portobello',
      'shiitake',
      'oyster mushrooms',
    ],
    fridgeDaysSafe: 7,
    iconKey: 'mushroom',
    version: RULES_VERSION,
  },
  {
    foodType: 'zucchini',
    displayName: 'Zucchini',
    category: 'produce',
    aliases: ['zucchini', 'summer squash', 'courgette', 'yellow squash'],
    fridgeDaysSafe: 7,
    freezerDaysSafe: 270,
    iconKey: 'zucchini',
    version: RULES_VERSION,
  },
  {
    foodType: 'avocado',
    displayName: 'Avocado',
    category: 'produce',
    aliases: ['avocado', 'hass avocado', 'guacamole'],
    fridgeDaysSafe: 3,
    counterHoursSafe: 48,
    iconKey: 'avocado',
    version: RULES_VERSION,
  },
  {
    foodType: 'onion',
    displayName: 'Onion',
    category: 'produce',
    aliases: ['onion', 'red onion', 'yellow onion', 'sweet onion', 'shallot', 'leek'],
    pantryDaysSafe: 60,
    iconKey: 'onion',
    version: RULES_VERSION,
  },
  {
    foodType: 'garlic',
    displayName: 'Garlic',
    category: 'produce',
    aliases: ['garlic', 'garlic cloves', 'garlic bulb', 'minced garlic'],
    pantryDaysSafe: 180,
    fridgeDaysSafe: 14,
    iconKey: 'garlic',
    version: RULES_VERSION,
  },
  {
    foodType: 'potato',
    displayName: 'Potato',
    category: 'produce',
    aliases: ['potato', 'russet potato', 'yukon gold', 'red potato', 'sweet potato', 'yam'],
    pantryDaysSafe: 30,
    fridgeDaysSafe: 90,
    iconKey: 'potato',
    version: RULES_VERSION,
  },
  {
    foodType: 'corn',
    displayName: 'Corn',
    category: 'produce',
    aliases: ['corn', 'corn on the cob', 'sweet corn', 'corn kernels'],
    fridgeDaysSafe: 3,
    freezerDaysSafe: 270,
    iconKey: 'corn',
    version: RULES_VERSION,
  },
  {
    foodType: 'berries',
    displayName: 'Berries',
    category: 'produce',
    aliases: ['strawberries', 'blueberries', 'raspberries', 'blackberries', 'mixed berries'],
    fridgeDaysSafe: 5,
    freezerDaysSafe: 365,
    iconKey: 'berry',
    version: RULES_VERSION,
  },
  {
    foodType: 'apple',
    displayName: 'Apple',
    category: 'produce',
    aliases: ['apple', 'fuji apple', 'gala apple', 'granny smith', 'honeycrisp'],
    fridgeDaysSafe: 42,
    counterHoursSafe: 168,
    iconKey: 'apple',
    version: RULES_VERSION,
  },
  {
    foodType: 'banana',
    displayName: 'Banana',
    category: 'produce',
    aliases: ['banana', 'plantain', 'ripe banana'],
    counterHoursSafe: 72,
    fridgeDaysSafe: 7,
    freezerDaysSafe: 90,
    iconKey: 'banana',
    version: RULES_VERSION,
  },
  {
    foodType: 'grapes',
    displayName: 'Grapes',
    category: 'produce',
    aliases: ['grapes', 'red grapes', 'green grapes', 'black grapes'],
    fridgeDaysSafe: 14,
    iconKey: 'grapes',
    version: RULES_VERSION,
  },
  {
    foodType: 'citrus',
    displayName: 'Citrus',
    category: 'produce',
    aliases: ['orange', 'lemon', 'lime', 'grapefruit', 'mandarin', 'clementine', 'tangerine'],
    fridgeDaysSafe: 21,
    counterHoursSafe: 168,
    iconKey: 'citrus',
    version: RULES_VERSION,
  },
  {
    foodType: 'mango',
    displayName: 'Mango',
    category: 'produce',
    aliases: ['mango', 'mango chunks', 'dried mango'],
    fridgeDaysSafe: 5,
    freezerDaysSafe: 180,
    iconKey: 'mango',
    version: RULES_VERSION,
  },
  {
    foodType: 'pineapple',
    displayName: 'Pineapple',
    category: 'produce',
    aliases: ['pineapple', 'pineapple chunks', 'pineapple slices'],
    fridgeDaysSafe: 4,
    freezerDaysSafe: 270,
    iconKey: 'pineapple',
    version: RULES_VERSION,
  },
  {
    foodType: 'watermelon',
    displayName: 'Watermelon',
    category: 'produce',
    aliases: ['watermelon', 'watermelon slices', 'cut watermelon'],
    fridgeDaysSafe: 5,
    iconKey: 'watermelon',
    version: RULES_VERSION,
  },
  {
    foodType: 'asparagus',
    displayName: 'Asparagus',
    category: 'produce',
    aliases: ['asparagus', 'asparagus spears'],
    fridgeDaysSafe: 5,
    freezerDaysSafe: 270,
    iconKey: 'asparagus',
    version: RULES_VERSION,
  },
  {
    foodType: 'green_beans',
    displayName: 'Green Beans',
    category: 'produce',
    aliases: ['green beans', 'snap peas', 'snow peas', 'string beans'],
    fridgeDaysSafe: 7,
    freezerDaysSafe: 270,
    iconKey: 'greens',
    version: RULES_VERSION,
  },

  // ── Grains / Bread ─────────────────────────────────────────────────────────
  {
    foodType: 'bread',
    displayName: 'Bread',
    category: 'grain',
    aliases: ['bread', 'sandwich bread', 'sourdough', 'baguette', 'rolls', 'pita'],
    pantryDaysSafe: 5,
    freezerDaysSafe: 90,
    iconKey: 'bread',
    version: RULES_VERSION,
  },
  {
    foodType: 'tortillas',
    displayName: 'Tortillas',
    category: 'grain',
    aliases: ['tortillas', 'flour tortillas', 'corn tortillas', 'wraps'],
    fridgeDaysSafe: 14,
    freezerDaysSafe: 90,
    iconKey: 'tortilla',
    version: RULES_VERSION,
  },
  {
    foodType: 'bagels',
    displayName: 'Bagels',
    category: 'grain',
    aliases: ['bagels', 'english muffins'],
    pantryDaysSafe: 3,
    freezerDaysSafe: 90,
    iconKey: 'bagel',
    version: RULES_VERSION,
  },
  {
    foodType: 'cooked_grains',
    displayName: 'Cooked Grains',
    category: 'grain',
    aliases: ['quinoa', 'farro', 'barley', 'couscous', 'bulgur', 'oats cooked'],
    fridgeDaysSafe: 5,
    freezerDaysSafe: 60,
    iconKey: 'grain',
    version: RULES_VERSION,
  },

  // ── Sauces & Condiments ────────────────────────────────────────────────────
  {
    foodType: 'tomato_sauce',
    displayName: 'Tomato Sauce',
    category: 'sauce',
    aliases: ['tomato sauce', 'marinara', 'pasta sauce', 'pizza sauce', 'salsa'],
    fridgeDaysSafe: 7,
    freezerDaysSafe: 90,
    iconKey: 'sauce',
    version: RULES_VERSION,
  },
  {
    foodType: 'salad_dressing',
    displayName: 'Salad Dressing',
    category: 'sauce',
    aliases: [
      'salad dressing',
      'vinaigrette',
      'ranch dressing',
      'caesar dressing',
      'italian dressing',
    ],
    fridgeDaysSafe: 14,
    iconKey: 'sauce',
    version: RULES_VERSION,
  },
  {
    foodType: 'hummus',
    displayName: 'Hummus',
    category: 'sauce',
    aliases: ['hummus', 'baba ganoush', 'tahini dip'],
    fridgeDaysSafe: 7,
    iconKey: 'dip',
    version: RULES_VERSION,
  },
  {
    foodType: 'gravy',
    displayName: 'Gravy',
    category: 'sauce',
    aliases: ['gravy', 'pan sauce', 'au jus'],
    fridgeDaysSafe: 4,
    freezerDaysSafe: 90,
    iconKey: 'sauce',
    version: RULES_VERSION,
  },
  {
    foodType: 'pesto',
    displayName: 'Pesto',
    category: 'sauce',
    aliases: ['pesto', 'basil pesto', 'sun-dried tomato pesto'],
    fridgeDaysSafe: 7,
    freezerDaysSafe: 90,
    iconKey: 'sauce',
    version: RULES_VERSION,
  },

  // ── Prepared / Meals ──────────────────────────────────────────────────────
  {
    foodType: 'prepared_meal',
    displayName: 'Prepared Meal',
    category: 'prepared',
    aliases: ['meal prep', 'meal kit', 'ready-made meal', 'takeout', 'delivery food'],
    fridgeDaysSafe: 4,
    freezerDaysSafe: 90,
    iconKey: 'meal',
    version: RULES_VERSION,
  },
  {
    foodType: 'casserole',
    displayName: 'Casserole',
    category: 'prepared',
    aliases: ['casserole', 'lasagna', 'baked pasta', 'enchiladas', 'moussaka'],
    fridgeDaysSafe: 4,
    freezerDaysSafe: 90,
    iconKey: 'casserole',
    version: RULES_VERSION,
  },
  {
    foodType: 'quiche',
    displayName: 'Quiche / Frittata',
    category: 'prepared',
    aliases: ['quiche', 'frittata', 'egg bake', 'strata'],
    fridgeDaysSafe: 4,
    freezerDaysSafe: 60,
    iconKey: 'egg',
    version: RULES_VERSION,
  },
  {
    foodType: 'stuffed_peppers',
    displayName: 'Stuffed Peppers',
    category: 'prepared',
    aliases: ['stuffed peppers', 'stuffed cabbage', 'stuffed squash'],
    fridgeDaysSafe: 4,
    freezerDaysSafe: 60,
    iconKey: 'pepper',
    version: RULES_VERSION,
  },

  // ── Baked Goods ────────────────────────────────────────────────────────────
  {
    foodType: 'muffins',
    displayName: 'Muffins',
    category: 'baked',
    aliases: ['muffins', 'cupcakes', 'scones', 'biscuits'],
    pantryDaysSafe: 3,
    freezerDaysSafe: 90,
    iconKey: 'muffin',
    version: RULES_VERSION,
  },
  {
    foodType: 'cake',
    displayName: 'Cake',
    category: 'baked',
    aliases: ['cake', 'birthday cake', 'cheesecake', 'pound cake', 'coffee cake'],
    fridgeDaysSafe: 5,
    freezerDaysSafe: 90,
    iconKey: 'cake',
    version: RULES_VERSION,
  },
  {
    foodType: 'cookies',
    displayName: 'Cookies',
    category: 'baked',
    aliases: ['cookies', 'brownies', 'bars', 'biscotti'],
    pantryDaysSafe: 7,
    freezerDaysSafe: 90,
    iconKey: 'cookie',
    version: RULES_VERSION,
  },
  {
    foodType: 'pie',
    displayName: 'Pie',
    category: 'baked',
    aliases: ['pie', 'tart', 'galette', 'cobbler', 'crisp'],
    fridgeDaysSafe: 5,
    freezerDaysSafe: 60,
    iconKey: 'pie',
    version: RULES_VERSION,
  },
  {
    foodType: 'pancakes_waffles',
    displayName: 'Pancakes / Waffles',
    category: 'baked',
    aliases: ['pancakes', 'waffles', 'crepes', 'french toast'],
    fridgeDaysSafe: 3,
    freezerDaysSafe: 60,
    iconKey: 'pancake',
    version: RULES_VERSION,
  },

  // ── Beverages ──────────────────────────────────────────────────────────────
  {
    foodType: 'juice',
    displayName: 'Juice',
    category: 'beverage',
    aliases: ['orange juice', 'apple juice', 'grape juice', 'lemonade', 'smoothie'],
    fridgeDaysSafe: 7,
    iconKey: 'juice',
    version: RULES_VERSION,
  },
  {
    foodType: 'cold_brew',
    displayName: 'Cold Brew Coffee',
    category: 'beverage',
    aliases: ['cold brew', 'iced coffee', 'coffee concentrate'],
    fridgeDaysSafe: 14,
    iconKey: 'coffee',
    version: RULES_VERSION,
  },
  {
    foodType: 'kombucha',
    displayName: 'Kombucha',
    category: 'beverage',
    aliases: ['kombucha', 'water kefir', 'jun tea'],
    fridgeDaysSafe: 30,
    iconKey: 'kombucha',
    version: RULES_VERSION,
  },

  // ── Misc ──────────────────────────────────────────────────────────────────
  {
    foodType: 'opened_can',
    displayName: 'Opened Canned Food',
    category: 'prepared',
    aliases: ['canned beans', 'canned tomatoes', 'canned soup', 'opened can'],
    fridgeDaysSafe: 4,
    iconKey: 'can',
    version: RULES_VERSION,
  },
  {
    foodType: 'cooked_beans',
    displayName: 'Cooked Beans / Legumes',
    category: 'prepared',
    aliases: ['cooked beans', 'lentils', 'chickpeas', 'black beans', 'kidney beans'],
    fridgeDaysSafe: 5,
    freezerDaysSafe: 180,
    iconKey: 'beans',
    version: RULES_VERSION,
  },
  {
    foodType: 'cooked_lentils',
    displayName: 'Cooked Lentils',
    category: 'prepared',
    aliases: ['lentils', 'red lentils', 'green lentils', 'french lentils', 'dal'],
    fridgeDaysSafe: 5,
    freezerDaysSafe: 180,
    iconKey: 'beans',
    version: RULES_VERSION,
  },
  {
    foodType: 'nuts_seeds',
    displayName: 'Nuts & Seeds',
    category: 'pantry',
    aliases: [
      'almonds',
      'walnuts',
      'pecans',
      'cashews',
      'sunflower seeds',
      'pumpkin seeds',
      'chia seeds',
    ],
    pantryDaysSafe: 180,
    fridgeDaysSafe: 365,
    freezerDaysSafe: 730,
    iconKey: 'nuts',
    version: RULES_VERSION,
  },
];

async function getCurrentVersion(): Promise<number | null> {
  const result = await ddb.send(
    new GetCommand({
      TableName: TABLE,
      Key: { PK: 'FOOD_RULES', SK: 'VERSION' },
      ProjectionExpression: '#v',
      ExpressionAttributeNames: { '#v': 'version' },
    }),
  );
  return (result.Item?.['version'] as number | undefined) ?? null;
}

async function publishRules(rules: FoodRule[]): Promise<void> {
  // Write rules in batches of 25
  for (let i = 0; i < rules.length; i += 25) {
    const batch = rules.slice(i, i + 25);
    await ddb.send(
      new BatchWriteCommand({
        RequestItems: {
          [TABLE]: batch.map((rule) => ({
            PutRequest: {
              Item: {
                PK: 'FOOD_RULES',
                SK: `RULE#${rule.foodType}`,
                entityType: 'FoodRule',
                updatedAt: new Date().toISOString(),
                ...rule,
              },
            },
          })),
        },
      }),
    );
  }

  // Write version record
  await ddb.send(
    new PutCommand({
      TableName: TABLE,
      Item: {
        PK: 'FOOD_RULES',
        SK: 'VERSION',
        version: RULES_VERSION,
        count: rules.length,
        publishedAt: new Date().toISOString(),
      },
    }),
  );
}

export const handler = async (): Promise<{
  published: number;
  version: number;
  skipped: boolean;
}> => {
  logger.info('food-rules-publish: starting', { targetVersion: RULES_VERSION });

  const currentVersion = await getCurrentVersion();
  if (currentVersion === RULES_VERSION) {
    logger.info('food-rules-publish: already at target version, skipping', {
      version: RULES_VERSION,
    });
    return { published: 0, version: RULES_VERSION, skipped: true };
  }

  await publishRules(FOOD_RULES);

  logger.info('food-rules-publish: done', { published: FOOD_RULES.length, version: RULES_VERSION });
  return { published: FOOD_RULES.length, version: RULES_VERSION, skipped: false };
};
